/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchoolsInstitutionsRouteImport } from './routes/schools-institutions'
import { Route as EmbroideryBrandingRouteImport } from './routes/embroidery-branding'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoryIndexRouteImport } from './routes/category.index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const SchoolsInstitutionsRoute = SchoolsInstitutionsRouteImport.update({
  id: '/schools-institutions',
  path: '/schools-institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbroideryBrandingRoute = EmbroideryBrandingRouteImport.update({
  id: '/embroidery-branding',
  path: '/embroidery-branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/contact-us': typeof ContactUsRoute
  '/embroidery-branding': typeof EmbroideryBrandingRoute
  '/schools-institutions': typeof SchoolsInstitutionsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/category/': typeof CategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/contact-us': typeof ContactUsRoute
  '/embroidery-branding': typeof EmbroideryBrandingRoute
  '/schools-institutions': typeof SchoolsInstitutionsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/category': typeof CategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/contact-us': typeof ContactUsRoute
  '/embroidery-branding': typeof EmbroideryBrandingRoute
  '/schools-institutions': typeof SchoolsInstitutionsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/category/': typeof CategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/contact-us'
    | '/embroidery-branding'
    | '/schools-institutions'
    | '/category/$slug'
    | '/product/$slug'
    | '/category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/contact-us'
    | '/embroidery-branding'
    | '/schools-institutions'
    | '/category/$slug'
    | '/product/$slug'
    | '/category'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/contact-us'
    | '/embroidery-branding'
    | '/schools-institutions'
    | '/category/$slug'
    | '/product/$slug'
    | '/category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  ContactUsRoute: typeof ContactUsRoute
  EmbroideryBrandingRoute: typeof EmbroideryBrandingRoute
  SchoolsInstitutionsRoute: typeof SchoolsInstitutionsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schools-institutions': {
      id: '/schools-institutions'
      path: '/schools-institutions'
      fullPath: '/schools-institutions'
      preLoaderRoute: typeof SchoolsInstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embroidery-branding': {
      id: '/embroidery-branding'
      path: '/embroidery-branding'
      fullPath: '/embroidery-branding'
      preLoaderRoute: typeof EmbroideryBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/': {
      id: '/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  ContactUsRoute: ContactUsRoute,
  EmbroideryBrandingRoute: EmbroideryBrandingRoute,
  SchoolsInstitutionsRoute: SchoolsInstitutionsRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  CategoryIndexRoute: CategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
